sudo: required
dist: trusty
language: node_js

node_js:
    - "6.11.2"

install:
  - npm install

cache:
  directories:
    - "node_modules"

script:
<<<<<<< HEAD
    - "npm test"
=======
    - "echo hello"
>>>>>>> 9551b9f5b2f785ccd5bbd88a3601b94de8cb7557
