sudo: required
dist: trusty
language: node_js

node_js:
    - "10.14.2"

notifications:
  webhooks: https://coveralls.io/webhook?repo_token=qlFs2tTsYawybdFiaR9zWv4zj7hQM6NBn

install:
  - npm install

cache:
  directories:
    - "node_modules"

script:
    - "npm test"

after_script:
    - "npm coveralls"

mail:
  recipients:
    - beiding110@gmail.com
    on_success: always
    on_failure: always
